version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}thompsonprojectwebapi
    restart: always
    build:
      context: .
      dockerfile: ThompsonProject.WebApi/Dockerfile
    depends_on:
      - proxy
    ports:
      - '8081:80'

  metrics:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - metricsdata:/data
    depends_on:
      - proxy
    ports:
      - '8083:80'

  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - db
      - proxy
    ports:
      - '8082:8080'

  wordpress:
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
      - proxy
    ports:
      - '8080:80'

  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxydata:/data
      - proxyssl:/etc/letsencrypt

volumes:
  proxydata:
  proxyssl:
  metricsdata:
  dbdata:
  wpdata: