version: '3.4'

services:
  metricslogger:
    image: nickmartin1ee7/nginx-seq-ingestionservice
    restart: always
    environment:
      - API_KEY
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/ps -aux | /usr/bin/rg ' +0:00 tail'"]
      retries: 3
      start_period: 3m
    volumes:
      - proxydata:/data/proxydata:ro

  metrics:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - metricsdata:/data
    depends_on:
      - proxy
    ports:
      - '10084:80'

  db:
    image: mariadb:latest
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql # Maintenance mode only
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - db
      - proxy
    ports:
      - '10083:8080'

  wordpress:
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    depends_on:
      - db
      - proxy
    ports:
      - '10082:80'

  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '10081:81'
      - target: 80
        published: 10080
        protocol: tcp
        mode: host
      - target: 443
        published: 10443
        protocol: tcp
        mode: host
    volumes:
      - proxydata:/data
      - proxyssl:/etc/letsencrypt


volumes:
  proxydata:
  proxyssl:
  metricsdata:
  dbdata:
  wpdata:
