version: '3.4'

services:
  webapi:
    image: thompsonprojectcr.azurecr.io/thompsonprojectwebapi:latest
    restart: always
    environment:
      - AppSettings__LoggingUri
      - AppSettings__LoggingKey
      - ConnectionStrings__Thompson
    depends_on:
      - proxy
    ports:
      - '8081:80'

  metrics:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - metricsdata:/data
    depends_on:
      - proxy
    ports:
      - '8082:80'

  db:
    image: mariadb:latest
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql # Maintenance mode only
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - db
      - proxy
    ports:
      - '8083:8080'

  wordpress:
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    depends_on:
      - db
      - proxy
    ports:
      - '8080:80'

  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxydata:/data
      - proxyssl:/etc/letsencrypt

volumes:
  proxydata:
  proxyssl:
  metricsdata:
  dbdata:
  wpdata:
