version: '3.4'

services:
  #webapi: # Disabled unless required
  #  image: thompsonprojectcr.azurecr.io/thompsonprojectwebapi:latest
  #  restart: always
  #  environment:
  #    - AppSettings__LoggingUri
  #    - AppSettings__LoggingKey
  #    - ConnectionStrings__Thompson
  #  depends_on:
  #    - proxy
  #  ports:
  #    - '8081:80'
  metricslogger: # TODO - Create image
    image: ubuntu:latest
    restart: always
    command: >
      bash -c "apt update && apt install dotnet6 curl ripgrep -y && dotnet tool install --global seqcli;
      $(while [ 1 ]; do o=`ps -aux | rg '0:00 tail.{10}'`>&1 && echo Tail running || echo Tail NOT running; sleep 30; done;) &
      echo \"Starting tail ingest...\";
      tail -n 0 -f /data/proxydata/logs/*.log | sed 's/==>.*//' | ./root/.dotnet/tools/seqcli ingest -s http://metrics -a ${AppSettings__LoggingKey} --invalid-data=ignore -x \"${SEQ_NGINX_EXT_PATTERN}\";
      echo \"Tail ingest exited!\";"
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/ps -aux | /usr/bin/rg '0+:0+ +tail.{10}'"]
      retries: 3
      start_period: 3m
    volumes:
      - proxydata:/data/proxydata:ro

  metrics:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - metricsdata:/data
    depends_on:
      - proxy
    ports:
      - '8082:80'

  db:
    image: mariadb:latest
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql # Maintenance mode only
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - db
      - proxy
    ports:
      - '8083:8080'

  wordpress:
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    depends_on:
      - db
      - proxy
    ports:
      - '8080:80'

  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxydata:/data
      - proxyssl:/etc/letsencrypt


volumes:
  proxydata:
  proxyssl:
  metricsdata:
  dbdata:
  wpdata: